-- create all databases needed for the competition

drop database hearst_challenge;

create database hearst_challenge;
	
connect hearst_challenge;

-- validation

create table sales_vd (
	wholesaler_key int not null primary key, 
	chain_key int not null, 
	store_key int not null, 
	issue_key int not null, 
	title_key int not null
	);

create table store_vd (
	chain_key int,
	store_key int,
	city varchar(255),
	ctry varchar(255),
	or_cot_desc varchar(255),
	zip_code int,
	zip_4 int,
	state varchar(255),
	store_number int,
	chain_or_cot_desc varchar(255),
	households int,
	individuals int,
	occupation_prof_technical int,
	occupation_sales_service int,
	occupation_farm_related int,
	occupation_blue_collar int,
	occupation_other int,
	occupation_retired int,
	occupation_unknown int,
	education_high_school_diploma int,
	education_some_college int,
	education_bachelor_degree int,
	education_graduate_degree int,
	education_less_than_high_school int,
	education_unknown int,
	age_18 int,
	age_19 int,
	age_20 int,
	age_21 int,
	age_22_to_24 int,
	age_25_to_29 int,
	age_30_to_34 int,
	age_35_to_39 int,
	age_40_to_44 int,
	age_45_to_49 int,
	age_50_to_54 int,
	age_55_to_59 int,
	age_60_to_64 int,
	age_65_to_69 int,
	age_70_to_75 int,
	age_75_ int,
	age_unknown int,
	gender_male int,
	gender_female int,
	gender_both int,
	gender_unknown int,
	marital_status_yes int,
	marital_status_no int,
	marital_status_unknown int,
	hsehld_status_head_of_household int,
	hsehld_status_spouse int,
	hsehld_status_young_adult int,
	hsehld_status_elderly_individua int,
	hsehld_status_other_adult int,
	income_under__15000 int,
	income__15000_to__24999 int,
	income__25000_to__34999 int,
	income__35000_to__49999 int,
	income__50000_to__74999 int,
	income__75000_to__99999 int,
	income__100000_to__124999 int,
	income__125000_to__149999 int,
	income__150000_to__174999 int,
	income__175000_to__199999 int,
	income__200000_to__249999 int,
	income__250000_ int,
	income_unknown int,
	homeowner int,
	renter int,
	homeowner_unknown int,
	dwelling_type_single_family_sfd int,
	dwelling_type_multi_fam_condo int,
	dwelling_type_marginal_multi_fa int,
	dwelling_type_po_box int,
	dwelling_type_unknown int,
	length_of_residence_under_1_yr int,
	length_of_residence_1_yr int,
	length_of_residence_2_to_5_yrs int,
	length_of_residence_6_to_10_yrs int,
	length_of_residence_10__yrs int,
	length_of_residence_unknown int,
	dwelling_size___1_unit int,
	dwelling_size___2_units int,
	dwelling_size___3_units int,
	dwelling_size___4_units int,
	dwelling_size___5_to_9_units int,
	dwelling_size___10_to_19_units int,
	dwelling_size___20_to_49_units int,
	dwelling_size___50_to_100_units int,
	dwelling_size___100__units int,
	dwelling_size___unknown int,
	mvh___under__101000 int,
	mvh____101000_to__200000 int,
	mvh____201000_to__300000 int,
	mvh____301000_to__500000 int,
	mvh____501000_to__999999 int,
	mvh____1000000_ int,
	mvh___unknown int,
	summarized_area_lvl_statistics_a decimal(7,2),
	summarized_area_lvl_statistics_b decimal(7,2),
	summarized_area_lvl_statistics_c decimal(7,2),
	summarized_area_lvl_statistics_d decimal(7,2),
	summarized_area_lvl_statistics_e decimal(7,2),
	summarized_area_lvl_statistics_f decimal(7,2),
	summarized_area_lvl_statistics_g decimal(7,2),
	summarized_area_lvl_statistics_h decimal(7,2),
	number_of_vehicles_in_zip_zip_4 int,
	number_of_hhs_with_a_vehicle int,
	number_of_hhs_without_a_vehicle int,
	number_of_new_cars int,
	number_of_new_light_trucks int,
	number_of_used_cars int,
	number_of_used_light_trucks int,
	avg_vehicle_msrp int,
	avg_current_vehicle_retail_valu int,
	mystery_element_a varchar(1),
	mystery_element_b	
	);

create table template_vd (
	store_key int not null, 
	title_key int not null, 
	yearmonth varchar(6) not null, 
	sales_total decimal(7,7)
	);

-- model